### ISSUE TITLE
Search for new Maintainer

### ISSUE THREAD

**Issue by danbruegge** [danbruegge/gatsby-plugin-stylelint#20]
Hi, i no longer use Gatsby and have no time to maintain this package.

Someone wants to take over and maintain it? Otherwise, I will archive this repo.

**Comment by ehannes** [comment]
Hi @danbruegge!

We are using this package. Might be interested in maintaining it.

Do you know what's needed to support Gatsby v. 3 and 4? Huge rewrites or just some small modifications? :slightly_smiling_face:

**Comment by danbruegge** [comment]
Hi, sadly not. I've used Gatsby last with v2, but it should be small modifications.

So in order to maintain I've checked what have to been done. You should fork this repo and also create a new package on npm. Because on npm this one is scoped to my username.

If this is done, I will archive this repo and deprecate the npm package with a link to the new package.

Sounds like a plan?

**Comment by ehannes** [comment]
@danbruegge sound like a plan indeed. It's more a question about time for us. Currently, this package actually works for our sites running both Gatsby 3 and 4, so I think the only thing one would need to do is to update the dependencies, but I'm not 100% sure... Since this package is still working for our sites, we have prioritized other things up until now. But let's keep in touch :)
