### ISSUE TITLE
Gatsby develop process exits if linter finds an error

### ISSUE THREAD

**Issue by jketcham** [danbruegge/gatsby-plugin-stylelint#4]
If there are already issues that stylelint will find when you run `gatsby develop`, the build process will exit with the following error message:

`There was an error compiling the html.js component for the development server.`

However, if you run `gatsby develop` while there are no preexisting issues, the build continues successfully. Then, if you introduce an issue the linter picks up, the gatsby develop process continues fine and just shows the error that it found.

I was wondering if this is a known behavior while using this plugin or if something sounds off. Ideally I'd like the build to not exit if an error is found. Thanks!

Versions I'm running:
- `stylelint`: 9.10.1
- `@danbruegge/gatsby-plugin-stylelint`: 3.4.0

**Comment by danbruegge** [comment]
Thanks for the info. This behavior is new to me. Will check it out.

**Comment by norin89** [comment]
@danbruegge any progress on this issue. It happens to me also.

**Comment by danbruegge** [comment]
I finally had the chance to look into this topic.

This plugin only passes the options to [stylelint-webpack-plugin](https://github.com/webpack-contrib/stylelint-webpack-plugin). Looks like it is deprecated, no changes since last year. :(

My findings:
+ it looks like `failOnError` gets ignored or the source is something else
+ get different error messages on `failOnError: true` and `failOnError: false`
+ i've locally updated all packages to the current version, sadly it didn't solved the issue.

Currently i don't have enough time to really track down the origin of this issue. Maybe someone else can help?

**Comment by danbruegge** [comment]
Maybe an older version of `stylelint-webpack-plugin` is working? @jketcham or @norin89 can you test this for me?

**Comment by norin89** [comment]
I created Local Gatsby Plugin to test it and using [`stylelint-bare-webpack-plugin`](https://github.com/cascornelissen/) instead of `stylelint-webpack-plugin` seems to FIX the issue.

**Comment by danbruegge** [comment]
@norin89 - I've created a PR #5, can you check it out? For me it isn't working.

**Comment by danbruegge** [comment]
@norin89 - any news?

**Comment by danbruegge** [comment]
I've merged PR #5 into master. Let me know if this is still an issue otherwise i will close this in the next year.

**Comment by danbruegge** [comment]
I will close the issue for know.
