### ISSUE TITLE
keeps breaking dev-server if any rule is broken despite configuration

### ISSUE THREAD

**Issue by vitordino** [danbruegge/gatsby-plugin-stylelint#9]
hey there, nice plugin :v:

it seems the options aren’t being respected, or i’m not being able to understand them correctly..

even with `emitError` / `emitWarning` / `failOnError` / `failOnWarning` all set to `false` and `quiet` set to `true`, if I edit any of the files and it doesn’t follow my stylelint rules, the dev-server sets to "FAILED"..

if the error is present before starting the server, it just quits the whole process.

**Comment by danbruegge** [comment]
Can you check if the current version works for you? And please check: https://github.com/danbruegge/gatsby-plugin-stylelint/issues/4 I never got feedback on this.

Also, can you check: https://www.npmjs.com/package/stylelint-bare-webpack-plugin, because this plugin only passes options down to the webpack plugin.

// Edit
I've tested it in my starter example project (https://github.com/danbruegge/gatsby-starter-minimal). With this code:
```
{
      resolve: "@danbruegge/gatsby-plugin-stylelint",
      options: {
        files: ["**/*.{js,jsx,ts,tsx}"],
        emitErrors: false,
      },
},
```

Result:
![image](https://user-images.githubusercontent.com/1296438/101356117-e64daf00-3897-11eb-8e29-435007c2b0de.png)

**Comment by vitordino** [comment]
amazing.. i got out of the project that was using `stylelint`, but i’ll definitely try to spin up something to test it out..

feel free to close this.. will ask to reopen if i can confirm it’s not fixed :v:
